version: '3'

volumes:
  pg_data_quiz:

services:
  db:
    image: postgres:13
    container_name: postgres
    volumes:
      - pg_data_quiz:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  backend:
    build: ./quiz_service
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
