# Generated by Django 3.2 on 2023-10-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.PositiveIntegerField(unique=True)),
                ('question_text', models.TextField()),
                ('question_answer', models.TextField()),
                ('created_at', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
