# Generated by Django 3.2 on 2023-10-11 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizquestion',
            old_name='question_answer',
            new_name='answer_text',
        ),
    ]
